### ISSUE TITLE
Crash when switching to a downloaded profile

### ISSUE THREAD

**Issue by AraFox** [Nexus-Mods/NMM-Test-Builds#27]
[TraceLog20160426172200.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/237641/TraceLog20160426172200.txt)

https://www.nexusmods.com/skyrim/profiles/1545/?tb=files&pUp=1

Downloaded, shows up in local profiles, but I can't switch to it. x3 tries, same error. I am on some hefty cold meds though, so if I did something wrong let me know.

**Comment by roamwild** [comment]
Value (first) cannot be null. 

I get this error too when switching to that profile.

[TraceLog20160426210430.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/237751/TraceLog20160426210430.txt)

Setting up listener on Nexus Mod Manager-SkyrimIpcServer/SkyrimListener at 2016-04-26 21:04:37
Adding mod: nxm://skyrim/profiles/1545/
Adding Profile to running instance of client: nxm://skyrim/profiles/1545/
Running Application.
Launch Commands:
    BOSS Command:  (IsNull=True)
    LOOT Command:  (IsNull=True)
    Wrye Bash Command:  (IsNull=False)
    TES5Edit Command:  (IsNull=False)
    FNIS Command:  (IsNull=False)
    BodySlide 2 Command:  (IsNull=False)
    Dual Sheat Redux Patch Command:  (IsNull=False)
    Patchus Maximus Command:  (IsNull=False)
Adding Profile to running instance of client: nxm://skyrim/profiles/1545/
Adding Profile to running instance of client: nxm://skyrim/profiles/1545/
Adding Profile to running instance of client: nxm://skyrim/profiles/1545/

Tracing an Unhandled Exception:
Exception: 
Message: 
    Value cannot be null.
Parameter name: first
Full Trace: 
    System.ArgumentNullException: Value cannot be null.
Parameter name: first
   at System.Linq.Enumerable.Except[TSource](IEnumerable`1 first, IEnumerable`1 second, IEqualityComparer`1 comparer)
   at Nexus.Client.MainFormVM.ExecuteProfileSwitch(Form p_frmParent)
   at Nexus.Client.MainFormVM.SwitchProfile(Form p_frmParent, IModProfile p_impProfile, Boolean p_booSilentInstall)
   at Nexus.Client.MainForm.spbProfiles_DropDownItemClicked(Object sender, ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStripDropDownItem.OnDropDownItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStripDropDown.OnItemClicked(ToolStripItemClickedEventArgs e)
   at System.Windows.Forms.ToolStrip.HandleItemClick(ToolStripItem dismissingItem)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

Running Threads (0)

**Comment by DuskDweller** [comment]
Fixed in the next release!
