### ISSUE TITLE
0.62.6 Crashed switching between local profiles (System.NullReferenceException: Object reference not set to an instance of an object.)

### ISSUE THREAD

**Issue by roamwild** [Nexus-Mods/NMM-Test-Builds#48]
NMM had a downloaded profile active http://www.nexusmods.com/fallout4/profiles/2155
which I had edited slightly in my local copy to remove a couple large texture mods.

NMM crashed  when I activated my own F4MUIA profile from the Main Toolbar 
top progress bar after 'Installing Mods'
either while 'Disabling current profile' or 'Activating new profile'

[TraceLog20160429205615.txt](https://github.com/Nexus-Mods/NMM-Test-Builds/files/243421/TraceLog20160429205615.txt)

Could not reproduce this crash after 5 or 6 attempts of the same operation(s)

I was making a note that this profile would download the wrong 'Main File' from the Nexus and then fail to activate it in the VirtualModConfig.xml because it had the 'wrong' mod archive name/ID. I switched back to my own main profile and the crash occurred during [Activating] sequence

When I restarted NMM, plugins from both profiles were present in the Plugins list but none were active.
The Mods tied to each profile were properly activated / deactivated.

Trace file has been created: TraceLog20160429205615.txt
Mod Manager Version: 0.62.6.0
OS version: Microsoft Windows NT 6.1.7601 Service Pack 1
Installed .NET Versions:
    CDF SP 0
    v2.0.50727 SP 2
    v3.0 SP 2
    v3.5 SP 1
    v4 SP 0
    v4.0 SP 0
    v4.5: 4.6 or later
Tracing is forced: False

Tracing an Unhandled Exception:
Exception: 
Message: 
    Object reference not set to an instance of an object.
Full Trace: 
    System.NullReferenceException: Object reference not set to an instance of an object.
   at Nexus.Client.PluginManagement.UI.PluginManagerControl.ManagedPlugins_CollectionChanged(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at System.Collections.Specialized.NotifyCollectionChangedEventHandler.Invoke(Object sender, NotifyCollectionChangedEventArgs e)
   at Nexus.Client.Util.Collections.ThreadSafeObservableList`1.RemoveAt(Int32 index)
   at Nexus.Client.PluginManagement.OrderLog.PluginOrderLog.TransactionEnlistment.Commit()
   at Nexus.Client.PluginManagement.PluginManager.RemovePlugin(Plugin p_plgPlugin)
   at Nexus.Client.PluginManagement.UI.PluginManagerVM.LoadOrderManager_ExternalPluginRemoved(Object sender, EventArgs e)
   at Nexus.Client.Games.Gamebryo.PluginManagement.LoadOrder.PluginOrderManager.FileWatcherOnDeletedLoose(Object source, FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.OnDeleted(FileSystemEventArgs e)
   at System.IO.FileSystemWatcher.CompletionStatusChanged(UInt32 errorCode, UInt32 numBytes, NativeOverlapped\* overlappedPointer)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped\* pOVERLAP)

Running Threads (0)

**Comment by DuskDweller** [comment]
Should be fixed in 0.62.9!
